### ISSUE TITLE
CurrentUser ID always returns 0

### ISSUE THREAD

**Issue by QFSW** [loicteixeira/gj-unity-api#75] opened 2017-07-22 09:36 UTC
Using GameJolt.API.Manager.Instance.CurrentUser.ID always returns 0, however GameJolt.API.Manager.Instance.CurrentUser.Name works just fine

**Comment by loicteixeira** [comment] 2017-07-22 11:04
Copying some of the discussion from GameJolt here so it might benefit some other users.

When you sign in a user, the callback is called when the authentication is successful, not when the user information are fetched. There is no built-in way to delay the callback at the moment but a solution is discussed in #48.

FWIW, `ID` is 0 and `Name` is available because the user was fetched by `Name`. If it has been fetched by `ID`, then `ID` would be available but `Name` wouldn't.

Closing this issue as it is essentially a duplicate of #48 (i.e. `CurrentUser.ID` does not always returns `0`, but is only available once the `User.Get` call has completed).

**Closed by loicteixeira** 2017-07-22 11:04 UTC
